# Generated by Django 3.2.6 on 2021-08-31 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import precios.models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default="nn", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ubic',
            field=models.CharField(default="no cargada", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='A',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='C',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Cg',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Cr',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Hp',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='M',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Mc',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Mp',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Mv',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Pa',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='PaD',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Pe',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='PeF',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='Troc',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='abrev',
            field=models.CharField(default="nn", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default="nn", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
            preserve_default=False,
        ),
    ]
