# Generated by Django 3.2.6 on 2021-08-31 20:33

from django.db import migrations, models
import precios.models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_auto_20210831_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
    ]
