# Generated by Django 3.2.6 on 2021-08-31 23:31

from django.db import migrations, models
import precios.models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0003_alter_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='Po',
            field=models.FloatField(default=0, validators=[precios.models.min_value]),
        ),
    ]
